name: Data CI
on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_REPO }}   # jika repo private
          fetch-depth: 0

      - name: List files
        run: ls -R

      # Validasi JSON (opsional, lewati jika tidak pakai JSON)
      - name: Validate JSON files
        run: |
          set -e
          shopt -s nullglob
          for f in **/*.json; do
            echo "checking $f"
            jq -e . "$f" > /dev/null
          done

      # Validasi GeoJSON (opsional, sama seperti JSON)
      - name: Validate GeoJSON files
        run: |
          set -e
          shopt -s nullglob
          for f in **/*.geojson; do
            echo "checking $f"
            jq -e . "$f" > /dev/null
          done


