name: Data CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clone datalokasi_maps (public)
        run: git clone https://github.com/tjx578/datalokasi_maps.git

      - name: List files (opsional)
        run: |
          ls -R
          ls -R datalokasi_maps || true

      - name: Validate JSON
        run: |
          set -e
          shopt -s globstar nullglob
          for f in datalokasi_maps/**/*.json; do
            echo "checking $f"
            jq -e . "$f" >/dev/null
          done

      - name: Validate GeoJSON
        run: |
          set -e
          shopt -s globstar nullglob
          for f in datalokasi_maps/**/*.geojson; do
            echo "checking $f"
            jq -e . "$f" >/dev/null
          done
