name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout with PAT
        if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_REPO }} 
          fetch-depth: 0
          submodules: true              
          persist-credentials: false

     
      - name: Checkout for forked PRs (no private deps)
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: false

      - name: Build
        run: |
          echo "jalankan build/test di sini"

