name: Process JSON Data

on:
  push:
    paths:
      - "raw-data/**.json"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run processing script
        run: |
          pip install --upgrade pip
          python process.py

      - name: Push results to output branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git fetch
          git checkout output || git checkout --orphan output

          mkdir -p output-json
          cp -r output-json/* output-json/ || true
          cp output-data.csv . || true

          git add output-json/ output-data.csv
          git commit -m "Update processed data" || echo "No changes"
          git push origin output
