name: Process JSON Data

on:
  push:
    paths:
      - "raw-data/**.json"
  workflow_dispatch:

permissions:
  contents: read   # push memakai PAT (GH_PAT), bukan GITHUB_TOKEN

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false   # kita push dengan PAT

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run processing script
        run: |
          python process.py

      # Simpan hasil sementara agar aman saat ganti branch
      - name: Stash artifacts
        run: |
          mkdir -p /tmp/artifacts
          if [ -d output-json ]; then cp -r output-json /tmp/artifacts/; fi
          if [ -f output-data.csv ]; then cp output-data.csv /tmp/artifacts/; fi
